server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food_recipe_app
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: 'your_app_email'
    password: 'your_app_password'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true